# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5001

@Email=administrator@localhost
@Password=Administrator1!
@Username=testuser
@BearerToken=<YourToken>

################################################################################
# Identity API Endpoints (Users Group)
################################################################################

# POST Users Register
POST {{Web_HostAddress}}/api/Users/register
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

# POST Users Login
POST {{Web_HostAddress}}/api/Users/login
Content-Type: application/json

{

  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

# POST Users Refresh
POST {{Web_HostAddress}}/api/Users/refresh
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "refreshToken": ""
}

###

# GET Users Info
GET {{Web_HostAddress}}/api/Users/info
Authorization: Bearer {{BearerToken}}

###

################################################################################
# Account Management Endpoints (Accounts Group)
################################################################################

# GET Account by Username or Email
GET {{Web_HostAddress}}/api/Accounts/{{Username}}
Authorization: Bearer {{BearerToken}}

###

# POST Create Account
POST {{Web_HostAddress}}/api/Accounts
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// CreateAccountCommand
{
  "username": "newuser",
  "email": "newuser@example.com"
}

###

# PUT Update Account
PUT {{Web_HostAddress}}/api/Accounts/1
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// UpdateAccountCommand
{
  "id": 1,
  "username": "updateduser",
  "email": "updated@example.com"
}

###

# DELETE Account by Username or Email
DELETE {{Web_HostAddress}}/api/Accounts/{{Username}}
Authorization: Bearer {{BearerToken}}

###

# DELETE Purge Accounts (Admin only)
DELETE {{Web_HostAddress}}/api/Accounts/purge
Authorization: Bearer {{BearerToken}}

###