// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServerGame.Infrastructure.Database.Domain;

#nullable disable

namespace ServerGame.Infrastructure.Database.Migrations.Domain
{
    [DbContext(typeof(DomainDbContext))]
    [Migration("20250612002325_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServerGame.Domain.Entities.BaseAuditableEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BaseAuditableEntity");

                    b.HasDiscriminator().HasValue("BaseAuditableEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ServerGame.Domain.Entities.Accounts.Account", b =>
                {
                    b.HasBaseType("ServerGame.Domain.Entities.BaseAuditableEntity");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastLoginInfo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("LastLoginInfo");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Username");

                    b.HasDiscriminator().HasValue("Account");
                });

            modelBuilder.Entity("ServerGame.Domain.Entities.Accounts.Account", b =>
                {
                    b.OwnsOne("ServerGame.Domain.ValueObjects.Accounts.BanInfo", "BanInfo", b1 =>
                        {
                            b1.Property<long>("AccountId")
                                .HasColumnType("bigint");

                            b1.Property<long?>("BannedById")
                                .HasColumnType("bigint")
                                .HasColumnName("BannedById");

                            b1.Property<DateTime?>("ExpiresAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("BanExpiresAt");

                            b1.Property<string>("Reason")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("BanReason");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("BanStatus");

                            b1.HasKey("AccountId");

                            b1.ToTable("BaseAuditableEntity");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.OwnsMany("ServerGame.Domain.ValueObjects.Accounts.Role", "Roles", b1 =>
                        {
                            b1.Property<long>("AccountId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .HasColumnType("text")
                                .HasColumnName("Role");

                            b1.HasKey("AccountId", "Value");

                            b1.ToTable("AccountRoles", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.Navigation("BanInfo");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
